name: Deploy Spring Boot to Azure

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build without running tests
        run: mvn clean install -DskipTests
        # Removed continue-on-error to stop if build fails

      - name: Upload Artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: examserver-0.0.1-SNAPSHOT
          path: examserver-0.0.1-SNAPSHOT.jar  # Correct path to JAR file at the root of the repo

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: examserver-0.0.1-SNAPSHOT  # Ensure matching name as used in the upload step
          path: .  # Download the artifact to the root of the project

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "SpringAppp"  # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./examserver-0.0.1-SNAPSHOT.jar  # Correct path to JAR in the root directory
